drop DATABASE LMS;
CREATE DATABASE LMS;
USE LMS;
CREATE TABLE user(
	id int NOT NULL AUTO_INCREMENT,
	userName VARCHAR(50) NOT NULL,
	email VARCHAR(100) NOT NULL,
	password VARCHAR(100),
	CONSTRAINT PRIMARY KEY(id)
);
CREATE TABLE member(
	mId INT (15 )NOT NULL AUTO_INCREMENT,
	mFName VARCHAR(100) NOT NULL,
	mLName VARCHAR(100) NOT NULL,
	dob DATE NOT NULL,
	gender VARCHAR(50) NOT NULL,
	address VARCHAR(50) NOT NULL,
	tel VARCHAR(60) NOT NULL,
	CONSTRAINT PRIMARY KEY(mId)
);
CREATE TABLE author(
	aId INT (15 )NOT NULL AUTO_INCREMENT,
	aFName VARCHAR(100) NOT NULL,
	aLName VARCHAR(100) NOT NULL,
	CONSTRAINT PRIMARY KEY(aId)
);
CREATE TABLE borrowed(
	mId INT (15 )NOT NULL,
	aId INT (15 )NOT NULL,
	bId INT (15 )NOT NULL AUTO_INCREMENT,
	borrowedDate DATE NOT NULL,
	receivedDate DATE NOT NULL,
	CONSTRAINT PRIMARY KEY(bId),
	CONSTRAINT FOREIGN KEY(mId) REFERENCES  member(mId)
	ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT FOREIGN KEY(aId) REFERENCES  author(aId)
	ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE book(
	bId INT (15) NOT NULL AUTO_INCREMENT,
	aId INT (15) NOT NULL,
	name VARCHAR(100) NOT NULL,
	qty INT (15) NOT NULL,
	price DECIMAL(10,2),
	CONSTRAINT PRIMARY KEY(bId),
	CONSTRAINT FOREIGN KEY(aId) REFERENCES  author(aId)
	ON DELETE CASCADE ON UPDATE CASCADE
);

